# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WebToolConfigUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dlgConfig(object):
    def setupUi(self, dlgConfig):
        dlgConfig.setObjectName("dlgConfig")
        dlgConfig.resize(600, 560)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/WebSerTestIcon/browser_window_38.581560283688px_1204645_easyicon.net.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgConfig.setWindowIcon(icon)
        self.gridLayout_4 = QtWidgets.QGridLayout(dlgConfig)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(dlgConfig)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.editWebIp = QtWidgets.QLineEdit(self.groupBox_2)
        self.editWebIp.setObjectName("editWebIp")
        self.horizontalLayout.addWidget(self.editWebIp)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.editPort = QtWidgets.QLineEdit(self.groupBox_2)
        self.editPort.setObjectName("editPort")
        self.horizontalLayout_2.addWidget(self.editPort)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWebAddress = QtWidgets.QTableWidget(self.groupBox)
        self.tableWebAddress.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWebAddress.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWebAddress.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWebAddress.setAlternatingRowColors(True)
        self.tableWebAddress.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWebAddress.setObjectName("tableWebAddress")
        self.tableWebAddress.setColumnCount(2)
        self.tableWebAddress.setRowCount(0)
        self.tableWebAddress.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        self.tableWebAddress.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.tableWebAddress.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWebAddress.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWebAddress, 0, 0, 2, 1)
        self.buttonAddAddress = QtWidgets.QPushButton(self.groupBox)
        self.buttonAddAddress.setObjectName("buttonAddAddress")
        self.gridLayout_2.addWidget(self.buttonAddAddress, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(dlgConfig)
        self.tabWidget.setCurrentIndex(0)

        self.buttonBox.rejected.connect(dlgConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgConfig)

    def retranslateUi(self, dlgConfig):
        _translate = QtCore.QCoreApplication.translate
        dlgConfig.setWindowTitle(_translate("dlgConfig", "配置"))
        self.groupBox_2.setTitle(_translate("dlgConfig", "Web服务器基本信息："))
        self.label.setText(_translate("dlgConfig", "WebSerivceIp:"))
        self.label_2.setText(_translate("dlgConfig", "端口号："))
        self.groupBox.setTitle(_translate("dlgConfig", "WebSerivceAddress:"))
        item = self.tableWebAddress.horizontalHeaderItem(0)
        item.setText(_translate("dlgConfig", "Web服务地址"))
        item = self.tableWebAddress.horizontalHeaderItem(1)
        item.setText(_translate("dlgConfig", "操作"))
        self.buttonAddAddress.setText(_translate("dlgConfig", "添加"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("dlgConfig", "web服务配置"))

if(__name__ == "__main__"):
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_dlgConfig()
    dlg = QtWidgets.QDialog()
    ui.setupUi(dlg)
    dlg.show()
    sys.exit(app.exec_())